workspace:
  base: /go
  path: src/github.com/airwallex/KubeAutoTestGoLang

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go test
      - go build

  docker:
    image: plugins/docker
    tags:
      - latest
      - 1.0
    repo: registry.dev.airwallex.awx:5000/KubeAutoTestingGoLang
    registry: registry.dev.airwallex.awx:5000
